### PR TITLE
Local Testing Infrastructure

### LINKED ISSUE #7098: Local testing should be straight forward
**CKAN version**
Current master 

**Describe the bug**
The Documentation for back-end testing (https://docs.ckan.org/en/2.9/contributing/test.html#back-end-tests) doesn't cover the CircleCI testing, nor how to replicate that on the local system. It's an automated system, based on docker, we should be able to easily run this locally, from this repo. 

The Documentation for manual testing (https://docs.ckan.org/en/2.9/contributing/test.html#manual-tests) is both out of date (IE has not been a going concern for a long time, and Safari has significant market share), and potentially in the wrong place (These are javascript coding standards, not strictly testing).

### PR DESCRIPTION
**Pull request by EricSoroos**
Fixes #7098 (partial)

### Proposed fixes:

Add a docker-compose version that mirrors, as exactly as possible, the CircleCI testing stack for running tests locally. 

The intention is that if someone has `docker-compose` installed, testing should be as simple as:
```cd config-test && ./setup.sh && ./execute.sh && ./teardown.sh```

### Features:

- [ ] includes tests covering changes
- [x] includes updated documentation
- [ ] includes user-visible changes
- [ ] includes API changes
- [ ] includes bugfix for possible backport

Please [X] all the boxes above that apply

### CODE REVIEW

**Comment by EricSoroos** [comment]
Feedback that I remember was that this was a good direction, but rename the directory to something else. Maybe `test-infra`?

**Comment by EricSoroos** [comment]
* Need to update to include doc build
* Merge in from master, modify for python8
* Readme is corrupted, need to fix

**Comment by EricSoroos** [comment]
This would need to be updated when #7886 lands

**Comment by wiredfool** [comment]
@wardi Can we get this into 2.11?

File: test-infrastructure/run_tests.sh [hunk 1]
```diff
@@ -0,0 +1,7 @@
+#!/bin/sh
+
+mkdir -p ~/junit
+python -m pytest $PYTEST_COMMON_OPTIONS
+
+#python -m pytest $PYTEST_COMMON_OPTIONS --splits 2 --group 1 --splitting-algorithm least_duration &
```
Comment (wardi) [inline test-infrastructure/run_tests.sh:6]:
```suggestion
#  to split work across containers and run tests in parallel like circleci use commands like:
#python -m pytest $PYTEST_COMMON_OPTIONS --splits 2 --group 1 --splitting-algorithm least_duration &
```

Comment (EricSoroos) [reply test-infrastructure/run_tests.sh:6]: The tricky thing here is that it the parallel tests don't work, because there's only one database. On circle-ci, it's running 4 complete stacks, so you can get the 4x speedup. Here the database test collide and fail badly.

**Comment by EricSoroos** [comment]
Great. I keep rebasing this up locally so that I can test in the replica of the circleci environment.

File: doc/contributing/test.rst [hunk 2]
```diff
@@ -20,12 +20,62 @@ tested manually.
...
+========
+
+.. parsed-literal::
+
+   ./teardown.sh
+
 
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-Install additional dependencies
+Vitrual Environment based tests
```
[the remark this answers is not in the document]
Comment (EricSoroos) [reply doc/contributing/test.rst]: Sigh. Spelling
